# Generated by Django 5.0.7 on 2024-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=20)),
                ('TransId', models.CharField(max_length=20, unique=True)),
                ('TransTime', models.CharField(max_length=50)),
                ('TransAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BusinessShortCode', models.CharField(max_length=20)),
                ('BillRefNo', models.CharField(max_length=20, unique=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=20, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=20, null=True)),
                ('MSISDN', models.CharField(max_length=500)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
