# Generated by Django 5.0.7 on 2024-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_receipting_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipting',
            name='BillRefNo',
            field=models.CharField(max_length=20),
        ),
    ]
